import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = dirname(fileURLToPath(import.meta.url));
const source = [
  (await readFile(join(root, 'calculations.mjs'), 'utf8')).replace(/^export /gm, ''),
  (await readFile(join(root, 'report-data.mjs'), 'utf8')).replace(/^export /gm, ''),
  (await readFile(join(root, 'src/app-ui.mjs'), 'utf8')).replace(/^import .*;\s*$/gm, '')
];

await writeFile(join(root, 'app.mjs'), [
  '// Volt Busbar Designer · self-contained browser bundle; generated by node build.mjs',
  ...source
].join('\n\n'));
